name: "Run unit test"

on:
  push:
    branches:
      - main

permissions: read-all|write-all

jobs:
  run-test:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "requirements.txt"
      - name: Run test
        run: pytest -vv
