name: 'Run test: All English'

on:
  push:
    branches: 
    - main
  
permissions:
  contents: read

jobs:
  run-test:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.3.0
    - name: Install test-runner
      run: pip install -r requirements.txt
    - name: Run test
      run: pytest -vv
